---
title: "Interactions"
author: "Sushanta Panda"
date: "6/29/2019"
output: html_document
---

```{r}
data = read.table("https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data",
                  quote = "\"",
                  comment.char = "",
                  stringsAsFactors = FALSE)
#Change the column name of the data set autompg
colnames(data) = c("mpg","cyl","disp","hp","wt","acc","year","origin","name")
#remove missing data stored as "?"
data = subset(data,data$hp != "?")
#remove the plymouth, as it causes issues
data = subset(data,data$name != "plymouth reliant")
#Assign the rowname, based on the engine, year and name
rownames(data) = paste(data$cyl,"cylinder",data$year,data$name)
#remove the variable for the name
data = subset(data,select = c("mpg","cyl","disp","hp","wt","acc","year","origin"))
#Change the horsepower from character to name
data$hp = as.numeric(data$hp)
#Creata a dummy variable for foreign vs domestic cars, domestic = 1
data$domestic = as.numeric(data$origin == 1)
#remove the 3 and 5 cylinder cars, as they arr very rare
data = data[data$cyl != 5,]
data = data[data$cyl != 3,]
#the following line would verify the remaining cylinder possibilities are 4,6,8
#unique(data$cyl)
#change cyl to a factor variable
data$cyl = as.factor(data$cyl) 
```

```{r}
str(data)
```

$$
Y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \epsilon
$$

where

- $Y$ is `mpg`, the fuel efficieny in miles per gallon 
- $x_1$ is `disp`, the displacement in cubic inches
- $x_2$ is `domestic` as described above, is a dummy variable

$$
x_2 = 
  \begin{cases}
  0 & \text{Domestic}\\
  1 & \text{Automatic}
  \end{cases}
$$


```{r}
mpg_disp_add = lm(mpg~disp+domestic,data=data)
int_dom = summary(mpg_disp_add)$coefficient[1,1]
int_for = summary(mpg_disp_add)$coefficient[1,1] + summary(mpg_disp_add)$coefficient[3,1]

slope_dom = summary(mpg_disp_add)$coefficient[2,1]
slope_for = summary(mpg_disp_add)$coefficient[2,1]

plot(mpg~disp, data = data,col = domestic + 1,pch = domestic + 1)
abline(int_dom,slope_dom,lwd=3,col=1,lty=1)
abline(int_for,slope_for,lwd=3,col=2,lty=2)
legend("topright",legend=c("domestic","foreign"),col=c(1,2),pch=c(1,2))

```